import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

// FFMpeg
import { createFFmpeg, fetchFile } from "@ffmpeg/ffmpeg";
// Tensorflow
import * as tf from "@tensorflow/tfjs";
import "@tensorflow/tfjs-backend-webgl";
import { loadGraphModel } from "@tensorflow/tfjs-converter";

const ffmpeg = createFFmpeg({
  log: true,
  // next local dev is finnicky and i can't get it to just load the local copy so we have grab an external copy for dev
  corePath: "https://unpkg.com/@ffmpeg/core@0.11.0/dist/ffmpeg-core.js",
});

const Home: NextPage = () => {
  async function test_loadFFmpeg() {
    if (!ffmpeg.isLoaded()) {
      await ffmpeg.load();
    } else {
      console.log("ffmpeg has already been loaded");
    }
  }

  async function test_loadModel() {
    const graphModel = await loadGraphModel("./tfjs_model/model.json");
    console.log("loaded model: ", graphModel);
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <button onClick={test_loadFFmpeg}>test ffmpeg</button>
          <button onClick={test_loadModel}>test model</button>
        </div>
      </main>
    </>
  );
};

export default Home;
